### ISSUE TITLE
Place the indicator on the right of the line number.

### ISSUE THREAD

**Issue by jcs090218** [Fuco1/indicators.el#7]
Hi, if I use `linum` the indicator is place on the right of the line number. But if I use `display-line-number-mode` then it displayed on the left. Is there a way to place the indicator on the right of the line number when using `display-line-number-mode`? Thank you!

**Comment by Fuco1** [comment]
I don't use any of the line number packages but I suspect one uses the margin feature and the other something else.  This package uses fringe to draw the indicators so that's something to be configured with respect to the others.

I think that configuration is not related to what this package does.

**Comment by Fuco1** [comment]
This is not possible because linum uses the margin which is rendered before the "fringe".
