### ISSUE TITLE
Function void `define-fringe-bitmap`

### ISSUE THREAD

**Issue by jcs090218** [Fuco1/indicators.el#8]
I think when https://github.com/Fuco1/indicators.el/blob/f62a1201f21453e3aca93f48483e65ae8251432e/indicators.el#L91
this line is executed. I got the error function void: `define-fringe-bitmap`. I think is because this function only built-in when the user compile with GUI version of Emacs. Is this line necessary? Is there other way to get around this? Thank you!

**Comment by Fuco1** [comment]
How would this work without the gui version when it draws to the margins? I don't think you can use it otherwise.

**Comment by jcs090218** [comment]
I was just thinking about avoiding the error when only the terminal version is installed!

**Comment by Fuco1** [comment]
I see.  It doesn't have to be top level and probably could move to the minor mode init and have some kind of lazy init.

**Comment by jcs090218** [comment]
Yeah, I don't know how you implemented this package. I read through your code and just a feeling that `define-fringe-bitmap` does not have to be on the top level? :D
